/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheGridRouteImport } from './routes/the-grid'
import { Route as ParticipantsRouteImport } from './routes/participants'
import { Route as IndexRouteImport } from './routes/index'

const TheGridRoute = TheGridRouteImport.update({
  id: '/the-grid',
  path: '/the-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsRoute = ParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/participants': typeof ParticipantsRoute
  '/the-grid': typeof TheGridRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/participants': typeof ParticipantsRoute
  '/the-grid': typeof TheGridRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/participants': typeof ParticipantsRoute
  '/the-grid': typeof TheGridRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/participants' | '/the-grid'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/participants' | '/the-grid'
  id: '__root__' | '/' | '/participants' | '/the-grid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ParticipantsRoute: typeof ParticipantsRoute
  TheGridRoute: typeof TheGridRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-grid': {
      id: '/the-grid'
      path: '/the-grid'
      fullPath: '/the-grid'
      preLoaderRoute: typeof TheGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants': {
      id: '/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof ParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ParticipantsRoute: ParticipantsRoute,
  TheGridRoute: TheGridRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
