/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheGridRouteImport } from './routes/the-grid'
import { Route as StorySyncRouteImport } from './routes/story-sync'
import { Route as ParticipantsRouteImport } from './routes/participants'
import { Route as LookupRouteImport } from './routes/lookup'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'

const TheGridRoute = TheGridRouteImport.update({
  id: '/the-grid',
  path: '/the-grid',
  getParentRoute: () => rootRouteImport,
} as any)
const StorySyncRoute = StorySyncRouteImport.update({
  id: '/story-sync',
  path: '/story-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantsRoute = ParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => rootRouteImport,
} as any)
const LookupRoute = LookupRouteImport.update({
  id: '/lookup',
  path: '/lookup',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/lookup': typeof LookupRoute
  '/participants': typeof ParticipantsRoute
  '/story-sync': typeof StorySyncRoute
  '/the-grid': typeof TheGridRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/lookup': typeof LookupRoute
  '/participants': typeof ParticipantsRoute
  '/story-sync': typeof StorySyncRoute
  '/the-grid': typeof TheGridRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/lookup': typeof LookupRoute
  '/participants': typeof ParticipantsRoute
  '/story-sync': typeof StorySyncRoute
  '/the-grid': typeof TheGridRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/lookup'
    | '/participants'
    | '/story-sync'
    | '/the-grid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/lookup'
    | '/participants'
    | '/story-sync'
    | '/the-grid'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/lookup'
    | '/participants'
    | '/story-sync'
    | '/the-grid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  LookupRoute: typeof LookupRoute
  ParticipantsRoute: typeof ParticipantsRoute
  StorySyncRoute: typeof StorySyncRoute
  TheGridRoute: typeof TheGridRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/the-grid': {
      id: '/the-grid'
      path: '/the-grid'
      fullPath: '/the-grid'
      preLoaderRoute: typeof TheGridRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story-sync': {
      id: '/story-sync'
      path: '/story-sync'
      fullPath: '/story-sync'
      preLoaderRoute: typeof StorySyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participants': {
      id: '/participants'
      path: '/participants'
      fullPath: '/participants'
      preLoaderRoute: typeof ParticipantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookup': {
      id: '/lookup'
      path: '/lookup'
      fullPath: '/lookup'
      preLoaderRoute: typeof LookupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  LookupRoute: LookupRoute,
  ParticipantsRoute: ParticipantsRoute,
  StorySyncRoute: StorySyncRoute,
  TheGridRoute: TheGridRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
